/*
  filename: integralui.base.value.js
  version : 20.2.0
  Copyright © 2020 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web Lite" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web Lite License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/lite/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
import IntegralUIObjectState from"./integralui.enums.js";import IntegralUIBase from"./integralui.base.js";class IntegralUIBaseValue extends IntegralUIBase{_ini(){super._ini();this._cVal=void 0;this._cntCS={};this._gnrCsNm="iui-basevalue";this._cntCSName=this._gnrCsNm+"-content"}_iniStyle(){this._dfSty={general:{disabled:this._gnrCsNm+"-disabled",focused:this._gnrCsNm+"-focused",normal:this._gnrCsNm,hovered:this._gnrCsNm+"-hovered",selected:this._gnrCsNm+"-selected"},content:{disabled:this._cntCSName+"-disabled",focused:this._cntCSName+"-focused",normal:this._cntCSName,hovered:this._cntCSName+"-hovered",selected:this._cntCSName+"-selected"}};this.refresh()}attributeChangedCallback(t,e,s){super.attributeChangedCallback(t,e,s)}static get properties(){return{value:{type:Number,reflect:!0}}}get value(){return this._cVal}set value(t){if(this._cVal!==t){const e=this._cVal;this._cVal=t;this._inkEv("valueChanged",{value:this._cVal});this.requestUpdate("value",e);this.updateLayout()}}_prvDgSt(t){t.preventDefault();t.stopPropagation()}async updateLayout(){await this._prcUpLt();this.performUpdate()}_prcUpLt(){let t=this;return new Promise(e=>{let s=setTimeout(function(){t._clRc={width:t._eRf.clientWidth,height:t._eRf.clientHeight};clearTimeout(s);e()},1)})}refresh(){this._uSty(this.controlStyle);this._uCtrCs();this._upCntCs();this.performUpdate()}_gDfSty(){return{general:this._gDfGnSty(),content:this._gDfCntSty()}}_gDfCntSty(){return this._dfSty&&this._dfSty.content?{disabled:this._dfSty.content.disabled,focused:this._dfSty.content.focused,hovered:this._dfSty.content.hovered,normal:this._dfSty.content.normal,selected:this._dfSty.content.selected}:{}}_gCntCs(){return this._cntCS}_gCntSty(t){if(this._cmnSrv)if(this._cmnSrv.isString(t))return t;else if(t)return{disabled:this._cmnSrv.isFieldAvailable(t.disabled,this._cntCSName+"-disabled"),focused:this._cmnSrv.isFieldAvailable(t.focused,this._cntCSName+"-focused"),hovered:this._cmnSrv.isFieldAvailable(t.hovered,this._cntCSName+"-hovered"),normal:this._cmnSrv.isFieldAvailable(t.normal,this._cntCSName),selected:this._cmnSrv.isFieldAvailable(t.selected,this._cntCSName+"-selected")};return this._gDfCntSty()}_upCntCs(){this._cntCS={};this._cntCS[this._cntCSName]=!0;if(this._opt.currentStyle&&this._opt.currentStyle.content){this._cntCS[this._opt.currentStyle.content.normal]=!0;if(this.state&IntegralUIObjectState.Disabled)this._cntCS[this._opt.currentStyle.content.disabled]=!0;else if(this.state&IntegralUIObjectState.Focused)this._cntCS[this._opt.currentStyle.content.focused]=!0;else if(this.state&IntegralUIObjectState.Selected)this._cntCS[this._opt.currentStyle.content.selected]=!0;else if(this.state&IntegralUIObjectState.Hovered)this._cntCS[this._opt.currentStyle.content.hovered]=!0}}_uSty(t){if(t)this._opt.currentStyle={general:this._gGnSty(t.general),content:this._gCntSty(t.content)};else this._opt.currentStyle=this._gDfSty()}}export default IntegralUIBaseValue;